import './globals.css'
import type { Metadata } from 'next'
import { Mitr } from 'next/font/google'
import {ReduxProvider} from '@/redux/provider'

const mitr = Mitr({ weight: '300', subsets: ['latin', 'thai'] })

export const metadata: Metadata = {
  title: 'Trading jounal',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
        <body className={`${mitr.className} bg-gray-100`}>
          <ReduxProvider>{children}</ReduxProvider>
        </body>
    </html>
  )
}
